# Generated by Django 6.0.1 on 2026-02-02 06:15

import django.db.models.deletion
import quran.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reciter_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('name_arabic', models.CharField(blank=True, max_length=100)),
                ('style', models.CharField(choices=[('hafs', 'Hafs'), ('warsh', 'Warsh'), ('qaloon', 'Qaloon'), ('duri', 'Al-Duri')], max_length=50)),
                ('audio_url_template', models.URLField(max_length=500)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Surah',
            fields=[
                ('number', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name_arabic', models.CharField(max_length=100)),
                ('name_english', models.CharField(max_length=100)),
                ('name_translation', models.CharField(max_length=100)),
                ('revelation_type', models.CharField(choices=[('meccan', 'Meccan'), ('medinan', 'Medinan')], max_length=20)),
                ('total_verses', models.PositiveIntegerField()),
                ('audio_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Ayah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('number_in_surah', models.PositiveIntegerField()),
                ('text_uthmani', models.TextField()),
                ('text_indopak', models.TextField(blank=True)),
                ('text_simple', models.TextField(blank=True)),
                ('transliteration', models.TextField(blank=True)),
                ('translation_en', models.TextField(blank=True)),
                ('translation_id', models.TextField(blank=True)),
                ('translation_ur', models.TextField(blank=True)),
                ('words_arabic', quran.models.JSONField(blank=True, default=list)),
                ('words_transliteration', quran.models.JSONField(blank=True, default=list)),
                ('words_translation', quran.models.JSONField(blank=True, default=list)),
                ('audio_url', models.URLField(blank=True, max_length=500, null=True)),
                ('audio_segments', quran.models.JSONField(blank=True, default=list)),
                ('segment_timestamps', quran.models.JSONField(blank=True, default=list)),
                ('page_number', models.PositiveIntegerField()),
                ('juz_number', models.PositiveIntegerField()),
                ('hizb_number', models.PositiveIntegerField()),
                ('rub_number', models.PositiveIntegerField(blank=True, null=True)),
                ('sajdah', models.BooleanField(default=False)),
                ('surah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verses', to='quran.surah')),
            ],
            options={
                'ordering': ['surah__number', 'number_in_surah'],
                'unique_together': {('surah', 'number_in_surah')},
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bookmark_type', models.CharField(choices=[('default', 'Default'), ('favorite', 'Favorite'), ('memorized', 'Memorized'), ('study', 'Study')], default='default', max_length=20)),
                ('ayah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_by', to='quran.ayah')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quran_bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'ayah')},
            },
        ),
        migrations.CreateModel(
            name='Tafsir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('ibn_kathir', 'Tafsir Ibn Kathir'), ('jalalayn', 'Tafsir al-Jalalayn'), ('qurtubi', 'Tafsir al-Qurtubi'), ('tabari', 'Tafsir al-Tabari'), ('modern', 'Modern Tafsir')], max_length=100)),
                ('text', models.TextField()),
                ('language', models.CharField(default='en', max_length=10)),
                ('ayah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tafsirs', to='quran.ayah')),
            ],
            options={
                'unique_together': {('ayah', 'source', 'language')},
            },
        ),
        migrations.CreateModel(
            name='UserNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ayah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notes', to='quran.ayah')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quran_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'ayah')},
            },
        ),
        migrations.CreateModel(
            name='WordMeaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_index', models.PositiveIntegerField()),
                ('arabic_word', models.CharField(max_length=100)),
                ('transliteration', models.CharField(max_length=200)),
                ('pronunciation_audio', models.URLField(blank=True, max_length=500, null=True)),
                ('meaning_en', models.TextField()),
                ('meaning_id', models.TextField(blank=True)),
                ('meaning_ur', models.TextField(blank=True)),
                ('root_word', models.CharField(blank=True, max_length=50)),
                ('part_of_speech', models.CharField(blank=True, max_length=50)),
                ('ayah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_meanings', to='quran.ayah')),
            ],
            options={
                'ordering': ['ayah', 'word_index'],
                'unique_together': {('ayah', 'word_index')},
            },
        ),
    ]
