# Generated by Django 6.0.1 on 2026-02-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ayah',
            name='translation_bn',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='surah',
            name='name_translation_bn',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='surah',
            name='name_translation_ur',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
