# Generated by Django 6.0.1 on 2026-02-04 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0002_ayah_translation_bn_surah_name_translation_bn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bismillah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_uthmani', models.TextField(default='بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ')),
                ('translation_en', models.TextField(default='In the name of Allah, the Entirely Merciful, the Especially Merciful.')),
                ('audio_url', models.URLField(default='https://everyayah.com/data/Alafasy_128kbps/001001.mp3')),
                ('words', models.JSONField(default=list)),
            ],
        ),
    ]
